{
	"version": 1545276664,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bg_splash_menu-sheet0.png",
		"images/decoration_image_background-sheet0.png",
		"images/decoration_splash_menu-sheet0.png",
		"images/shadow_effect_splash_screen-sheet0.png",
		"images/light-sheet0.png",
		"images/game_title-sheet0.png",
		"images/play_button-sheet0.png",
		"images/bg_loading-sheet0.png",
		"images/loading_bar.png",
		"images/loading_background_bar-sheet0.png",
		"images/info_button-sheet0.png",
		"images/icon_found-sheet0.png",
		"images/background_game_hud-sheet0.png",
		"images/time_background_bar-sheet0.png",
		"images/time_bar.png",
		"images/icon_level-sheet0.png",
		"images/audio_button-sheet0.png",
		"images/audio_button-sheet1.png",
		"images/backward_button-sheet0.png",
		"images/bg_selectlevel-sheet0.png",
		"images/table_of_levels_ui-sheet0.png",
		"images/select_level_title-sheet0.png",
		"images/levels_icon-sheet0.png",
		"images/levels_icon-sheet1.png",
		"images/image_of_differences-sheet0.png",
		"images/difference_1-sheet0.png",
		"images/particles-sheet0.png",
		"images/particles-sheet1.png",
		"images/black_background-sheet0.png",
		"images/circle_of_light_effect-sheet0.png",
		"images/fog_purple_effect-sheet0.png",
		"images/restart_menu_button-sheet0.png",
		"images/congratulations_menu-sheet0.png",
		"images/stars_menu_congatulations-sheet0.png",
		"images/exit_menu_button-sheet0.png",
		"images/go_to_next_level_button-sheet0.png",
		"images/stars_explosion_effect-sheet0.png",
		"images/you_lose_stars-sheet0.png",
		"images/you_lose_menu-sheet0.png",
		"images/backward_menu_button-sheet0.png",
		"images/informations_image-sheet0.png",
		"images/play_again_menu_text-sheet0.png",
		"images/go_to_next_level_menu_text-sheet0.png",
		"images/informations_title-sheet0.png",
		"media/congratulations sound.ogg",
		"media/button sound.ogg",
		"media/find sound.ogg",
		"media/level fail.ogg",
		"media/game sound.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}